#
# Copyright Siemens AG, 2016. Part of the SW360 Portal Project.
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved. This file is offered as-is,
# without any warranty.
#

sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - curl -o datahandler-1.6.0-SNAPSHOT.jar https://toedter.com/download/sw360/datahandler-1.6.0-SNAPSHOT.jar
  - mvn install:install-file -Dfile=datahandler-1.6.0-SNAPSHOT.jar -DgroupId=org.eclipse.sw360 -DartifactId=datahandler -Dversion=1.6.0-SNAPSHOT -Dpackaging=jar

script:
  - ./gradlew clean build
