sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

before_script:
  - curl http://toedter.com/download/sw360/datahandler-1.6.0-SNAPSHOT.jar
  - mvn install:install-file -Dfile=datahandler-1.6.0-SNAPSHOT.jar

script:
  - ./gradlew build
